version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/ableron-js'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'maven'
    directory: '/ableron-java'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify'
    schedule:
      interval: 'monthly'
