version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/ableron-js'
    schedule:
      interval: 'weekly'
    groups:
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: 'maven'
    directory: '/ableron-java'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'maven'
    directory: '/ableron-spring-boot-2'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'org.springframework:spring-webmvc'
        versions: [ '>=6.0.0' ]
      - dependency-name: 'org.springframework.boot:*'
        versions: [ '>=3.0.0' ]
  - package-ecosystem: 'maven'
    directory: '/ableron-spring-boot-3'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/ableron-express'
    schedule:
      interval: 'weekly'
    groups:
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: 'npm'
    directory: '/ableron-fastify'
    schedule:
      interval: 'weekly'
    groups:
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify'
    schedule:
      interval: 'weekly'
    groups:
      testcontainers:
        applies-to: version-updates
        patterns:
          - "org.testcontainers:*"
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java17'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java17-spring-boot-3'
    schedule:
      interval: 'weekly'
    groups:
      spring-boot:
        applies-to: version-updates
        patterns:
          - "org.springframework.boot*"
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java21'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java21-spring-boot-3'
    schedule:
      interval: 'weekly'
    groups:
      spring-boot:
        applies-to: version-updates
        patterns:
          - "org.springframework.boot*"
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java11-spring-boot-2'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'org.springframework.boot*'
        versions: [ '>=3.0.0' ]
    groups:
      spring-boot:
        applies-to: version-updates
        patterns:
          - "org.springframework.boot*"
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java21-spring-boot-2'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'org.springframework.boot*'
        versions: [ '>=3.0.0' ]
    groups:
      spring-boot:
        applies-to: version-updates
        patterns:
          - "org.springframework.boot*"
