version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/ableron-js'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'maven'
    directory: '/ableron-java'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'maven'
    directory: '/ableron-spring-boot-2'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'org.springframework:spring-webmvc'
        update-types: ['version-update:semver-minor']
      - dependency-name: 'spring-boot.version'
        update-types: ['version-update:semver-minor']
      - dependency-name: 'org.springframework.boot:spring-boot-starter-parent'
        update-types: ['version-update:semver-minor']
  - package-ecosystem: 'maven'
    directory: '/ableron-spring-boot-3'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/ableron-express'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/ableron-fastify'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java17'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java17-spring-boot-3'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java21'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/ableron-verify/java21-spring-boot-3'
    schedule:
      interval: 'weekly'
