FROM gradle:8-jdk11

COPY ./ableron-java /opt/ableron-java
WORKDIR /opt/ableron-java
RUN ./mvnw install

COPY ./ableron-spring-boot-2 /opt/ableron-spring-boot-2
WORKDIR /opt/ableron-spring-boot-2
RUN ./mvnw install

COPY ./ableron-verify/java11-spring-boot-2 /opt/ableron-verify
WORKDIR /opt/ableron-verify

ENTRYPOINT ["gradle", "bootRun"]
