FROM node:22-alpine

COPY ./ableron-js /opt/ableron-js
WORKDIR /opt/ableron-js
RUN npm install
RUN npm run build

COPY ./ableron-express /opt/ableron-express
WORKDIR /opt/ableron-express
RUN npm install /opt/ableron-js
RUN npm install
RUN npm run build

COPY ./ableron-verify/nodejs22-express4-cjs /opt/ableron-verify
WORKDIR /opt/ableron-verify
RUN npm install /opt/ableron-js
RUN npm install /opt/ableron-express
RUN npm install

ENTRYPOINT ["npm", "run", "start"]
