FROM gradle:8.13-jdk21

COPY ./ableron-java /opt/ableron-java
WORKDIR /opt/ableron-java
RUN ./mvnw install -DskipTests=true

COPY ./ableron-spring-boot-2 /opt/ableron-spring-boot-2
WORKDIR /opt/ableron-spring-boot-2
RUN ./mvnw install -DskipTests=true

COPY ./ableron-verify/java21-spring-boot-2 /opt/ableron-verify
WORKDIR /opt/ableron-verify

ENTRYPOINT ["gradle", "bootRun"]
