name: "ableron-verify: ableron-fastify @ Node.js 24 & Fastify 5"

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ableron-verify
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
          cache-dependency-path: ableron-verify/build.gradle
      - run: ./gradlew test --tests '*.NodeJs24Fastify5Spec' --info
