name: ableron-fastify

on: push

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nodeVersion: [20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
          cache: npm
          cache-dependency-path: ableron-fastify/package-lock.json
      - run: npm run test:ableron-fastify
