name: ableron-js-publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ableron-js
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ableron-js/package-lock.json
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
