name: ableron-fastify-publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ableron-fastify
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ableron-fastify/package-lock.json
          registry-url: https://registry.npmjs.org
      - name: Remove package-lock.json as it may contain OS specific dependency of @rollup/rollup-* and thus needs to be rewritten
        run: rm -rf package-lock.json && npm install
      - run: npm run build
      - run: npm test
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
