name: ableron-spring-boot-3

on: push

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        javaVersion: [17, 21, 22, 23]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ableron-spring-boot-3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: temurin
          cache: maven
          cache-dependency-path: ableron-spring-boot-3/pom.xml
      - run: mvn -V --batch-mode --update-snapshots verify
  release:
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ableron-spring-boot-3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          cache-dependency-path: ableron-spring-boot-3/pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          cache-dependency-path: ableron-spring-boot-3/pom.xml
          server-id: ossrh # value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_PASSWORD # env variable for password in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Publish to Apache Maven Central
        run: mvn --batch-mode --update-snapshots deploy -Prelease -DskipTests=true
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
